pipeline {
  agent any

  stages {
    stage('Terraform Init & Apply') {
      steps {
        dir('terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Configure with Ansible') {
      steps {
        dir('ansible') {
          sh 'ansible-playbook -i inventory.ini playbook.yml'
        }
      }
    }

    stage('Test Deployment') {
      steps {
        sh 'curl http://localhost:8080'
      }
    }
  }
}
